name: A Basic Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run a one line script
        run: echo "Hello, world!"

      - name: Run a multi-line script
        run: |
          echo "Add other actions to build",
          echo "test, and deploy your project".

  build-db:
    runs-on: windows-latest
    steps:
      - run: echo "from windows runner API"

  packaging:
    needs: [build-app, build-db]
    runs-on: macos-latest
    steps:
      - run: echo "from macos runner"