name: Passing values to next step

on: workflow_dispatch

jobs:
  passing-values:
    runs-on: ubuntu-latest
    steps:
      - name: setting the value using env variables
        run: echo "variableName=variableValue" >> $GITHUB_ENV

      - name: creating variables
        id: var_source_step
        run: |
          echo "Performing a random task"
          echo "::set-output name=var1_name::techskool"
          echo "::set-output name=var2_date::$(date +'%Y-%m-%d-%H-%M-%S')"

      - name: using the variables
        run: |
          echo "Printing the values"
          echo variableName: ${{ env.variableName}}
          echo var1_name: ${{ steps.var_source_step.outputs.var1_name }}
          echo var2_date: ${{ steps.var_source_step.outputs.var2_date }}